# Generated by Django 4.2.5 on 2024-01-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_shakk', max_length=12),
        ),
    ]
