# Generated by Django 4.2.5 on 2024-01-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$c9PXULJvSCzotNDZ7xOpTb$AdQQjkeSoMCcMojxI5qZi0RNeYIBnXB+SrkLNMoZ2NA=', max_length=12),
        ),
    ]
