# Generated by Django 4.2.5 on 2024-01-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$CAa15IspsNXdEtB9ERC5Qk$QBs2aXG5xpVcv+ICTSkJOMqBfK+f6BBcFczuMcTL7y8=', max_length=12),
        ),
    ]
