# Generated by Django 4.2.5 on 2024-01-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_student_last_login_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$zOaglbZ7CjFUh5RsrqTc37$LN5tTMHxePL+moljC58SSZkdwM6kz5G0K0jxbN3Ak4M=', max_length=12),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='cId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='sId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
