# Generated by Django 4.2.5 on 2024-01-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_course_teacher_alter_student_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$ooV7BnOFoP5Pj0LQ5TbSVZ$I5ZNCS/zUfwokSuSg4eBe+YE2eyZWLzc6hTLT6r4YuI=', max_length=12),
        ),
    ]
