# Generated by Django 4.2.5 on 2024-01-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$Xwcs3L0JN373kfaeGQ0FgJ$7vyWvDAPcKKvYEWDX+rC+/ib9NMCwiUYGEE7XnZRcJ8=', max_length=12),
        ),
    ]
