# Generated by Django 4.2.5 on 2024-01-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_teacher_last_login_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$fNfgyBiJgZk9JB20V1zpe3$hGWbmctKGZSt9s/rhHZwGkLUjb0vWnR0VJnQYA1axjo=', max_length=12),
        ),
    ]
